default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: restaurant_menu_app_development

test:
  <<: *default
  database: restaurant_menu_app_test

production:
  <<: *default
  database: restaurant_menu_app_production
  url: <%= ENV["DATABASE_URL"] %>
