source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.4.4"

gem "rails", "~> 8.0.2"
gem "pg", "~> 1.1"
gem "puma", "~> 6.0"
gem "bootsnap", ">= 1.4.4", require: false
gem "rack-cors"
gem "jsonapi-serializer"
gem "rack-attack"

group :development, :test do
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails", "~> 6.2"
  gem "faker", "~> 3.2"
  gem "pry-rails"
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :test do
  gem "shoulda-matchers", "~> 5.3"
  gem "database_cleaner-active_record"
  gem "webmock"
  gem "vcr"
end

group :development do
  gem "listen", "~> 3.3"
  gem "spring"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
end

gem "thruster", "~> 0.1.15"
